project:
  type: website

website:
  title: "EDLD 651 Final Presentation"
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - text: "Reflection"
        file: reflection.qmd
      - text: "Findings"
        file: findings.qmd
      - text: "Next"
        file: next.qmd
      - text: "Final Paper"
        file: scripts/EDLD651-Final_Paper.qmd
        
        
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

