---
title: "Reflection"
---

::: panel-tabset
## Elyse Calhoun

1.  Challenges faced

    -   Understanding exactly what we were supposed to do for the Final Paper
    -   Switching data sets during the Thanksgiving Break
    -   Attempting to change variable names in a table
    -   Trying to navigate R, github, and gitkraken in the correct order

2.  Victories

    -   Discovering that I messed up the qmd file trying to change variable names on a table, catching the mistake before pushing it back out to the group.
    -   Teamwork makes the dream work.

3.  Current Challenges

    -   Gathering enough information to complete the final paper.

## Frances Jess

1.  Challenges faced

    -   Selecting a data set that was not excessively complicated but also not too clean 
    -   Gaining confidence in R syntax across multiple functions 
    -   Moving between Github, GitKraken, and RStudio 

2.  Victories

    -   Managed to collaborate remotely! 
    -   Problem solved as a group 
    -   Able to diagnose problems more quickly 

3.  Current Challenges

    -   Fluency in R language - I still have to review slides just about every time I work on an assignment to remember the proper syntax!

## Yitong Jiang

1.  Challenges faced

    -   Find a data set that we are familiar with the topic and are interested in exploring it.

2.  Victories

    -   Great communication in the team.
    -   Everyone is willing to share the workloads.

3.  Current Challenges

    -   Create a figure for Research question 3: Is there a difference in wage depending on whether you lived near a college?

## Eunji Kong

1.  Challenges Faced

    -   Working collaboratively on GitHub (confused with branches)

2.  Victories

    -   Working collaboratively on the analysis
    -   Making website using Quarto

3.  Current Challenges

    -   Designing the website

:::
