---
title: "EDLD Final Project v2"
author: 
  - Frances Pinkham 
  - Eunji Kong 
  - Elyse Calhoun 
  - Yitong Jiang
# Above I edited how you listed authors. With this edit, quarto now recognizes that there are multiple authors. Previously, as written, quarto recognized one author whose name was everything inside the quotes.
abstract: "This is where abstract is pasted" 
# In quarto, you paste the abstract in the yaml. 
format: html
editor: visual
# Would you consider a specific theme? When I rendered the file, its theme was a bit off, not sure if it is by design. 
execute: 
  eval: true # change to false before final submission so code is not evaluated; leave as true for now 
  echo: true
  message: false # will not render messages
  warning: false # will not render warnings 
embed-resources: true
code-fold: true
---

```{r}
#| include: false
library(tidyverse)
library(here)
library(rio)
library(modelsummary)
library(janitor)
```

```{r}
#| label: loading data 
schooling <- import(here("data","Schooling.csv")) %>% 
  as_tibble() %>% 
  clean_names()

# I imported the data as a tibble and used the janitor package to run clean names. Upon closer examination, these two functions did not change much from your dataset. 
```

```{r}
schoolingsub <- schooling %>%
  select(rownames,ed76, daded, momed, wage76, iqscore, age76, nearc2, nearc4)

```

```{r}
schoolingsub1 <- schoolingsub |> 
  mutate(near_college = ifelse(nearc2 == "yes" & nearc4 =="yes", "near_colleges", 
                               ifelse(nearc2 == "yes" & nearc4 =="no","near_cc", 
                                      ifelse(nearc2 == "no" & nearc4 =="yes","near_4yr", "not_near_college")))) 

# In the above code, case when is also an option 
```

```{r}
schoolingsub1 <- schoolingsub1 %>%
  pivot_longer(
    cols = c(daded,momed),
    names_to = "parent",
    values_to = "par_education")

schoolingsub1$parent <- gsub("daded", "dad", schoolingsub1$parent)

schoolingsub1$parent <- gsub("momed", "mom", schoolingsub1$parent)
```

Demographics

```{r}
datasummary_skim(schoolingsub1 |> 
                   pivot_wider (names_from = parent,
                                values_from = par_education) |> 
                   select(-rownames),
                 histogram = FALSE)
```

Research question 1: What is the relationship between parent education and participant's education?

### Plot 1

```{r}
schoolingsub1 |> 
  ggplot(aes(par_education, ed76, color = parent)) +
  geom_smooth(method = lm, se = FALSE) +
  labs(title = "Relationship between Parent and Participant Education",
       subtitle = "From 1976 Survey",
       x = "Parental Education (yrs)",
       y = "Participant Education (yrs)",
       color = "Parent"
       ) + 
  theme_minimal() 

```

Research question 2: What is the relationship between parent education and participant's wage?

### Plot 2
```{r}
schoolingsub1 |> 
  ggplot(aes(par_education, wage76, color = parent)) +
  geom_smooth(method = lm, se = FALSE) +
   labs(title = "Relationship between Parent Education and Participant Wages",
       subtitle = "From 1976 Survey",
       x = "Parental Education (yrs)",
       y = "Participant Wages (cents/hr)",
       color = "Parent"
       )  + 
  theme_minimal() 

# Just a thought, would you consider re-coding education as a categorical variable, i.e., less than high school, high school diploma, some college, bachelor's degree or some other variation. While looking at the data, I had a thought that a histogram might better display your data.  
```

Research question 3: Is there a difference in wage depending on whether you lived near a college?

### Table 1
```{r}
schoolingsub1$near_college <- gsub("near_4yr", "Near 4-year College", schoolingsub1$near_college)

schoolingsub1$near_college <- gsub("near_cc", "Near Community College", schoolingsub1$near_college)

schoolingsub1$near_college <- gsub("near_colleges", "Near 4-year  and Community College", schoolingsub1$near_college)

schoolingsub1$near_college <- gsub("not_near_college", "Not Near College", schoolingsub1$near_college)

schoolingsub1 %>%   
  group_by(near_college) |> 
  summarize(avg_wage = mean(wage76, na.rm = TRUE)/100) |>
  rename("Proximity to College" = near_college, "Participant Average Wage per Hour" = avg_wage) %>%
DT::datatable()
```